name: CIv2

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v1
    
    - name: Setup Stack
      uses: mstksg/setup-stack@v2
    
    - name: Cache Stack downloads
      uses: actions/cache@v1
      env:
        cache-name: cache-stack-modules
      with:
        path: /home/runner/.stack/
        key: "asfadsgfads"
      
    - name: stack install, build and test
      run: |
        stack test
